### ISSUE TITLE
What is meaning of backend?

### ISSUE THREAD

**Issue by cooldesigns** [treeform/fidget#1]
Is the output? Or Input?

I am searching a super fast html-css renderer engine via OpenGL, OpenGL ES, Metal, Vulkan works on ios and android. Also web can be done with WebGL. Because CSS3 API is so amazing so powerful.

I analyzed xamarin, flutter, react, vue, ios api, android api, cordova, fusetools but none is right.
Flutter rending on skia engine and fusetools rendering on opengl but there is no way to use any libraries or templates. Also CSS isn't available. So I have to develop all the things over. 

> Why not direct design to opengl rendering?
- There are a tons of designs systems so it's usefull. https://adele.uxpin.com/
- There are tons of css snippets, tons of animation libraries
- There are figma to html, sketch to html like converters staying already
> When design to opengl rendering usefull?
- When you have to code your design but it can be done with design to html than html to rendering

So both are required.

The solution steps:
1. Design to code
2. Code to webGL, OpenGL etc.

OR just the opposite

1. Render react components in sketch (the tool by airbnb) only available for react.
2. Import sketch files in figma. Both of converted and handmades.
3. Render figma files in a 2d engine.

Which way possible? Which way we need to go? I think we can find the right way and create a practical solution.

**Comment by treeform** [comment]
Backend means the system it uses to interact with UI components. So in a way its both input and output to the UI you build.

> I am searching a super fast html-css renderer engine via OpenGL, OpenGL ES, Metal, Vulkan works on ios and android. Also web can be done with WebGL. Because CSS3 API is so amazing so powerful.

So you want to give it html+css and you want it to use the GPU? Your best bet is problem some thing like https://ultralig.ht/. 

Personally I want to get a way from the crazy complex thing that HTML+CSS is. I want to have a few simple concepts - almost Axioms. I want the few concepts to render to HTML/OpenGL/Canvas... wherever else stuff can be rendered too. 

My main goal is to minimize boring layout stuff in code and leverage design tools like Figma instead.

I did not know about https://github.com/airbnb/react-sketchapp. They seem to go the opposite way, instead of drawing stuff and generating code, they are writing code to generate stuff in sketch. 

Ideally the process is:
* Design the stuff you want in Figma 
* Generate code from Figma files
* Modify generated code to give it interactivity. 
* When compiling your app you will target a backend like HTML, OpenGL, Cairo.

What exactly do you want me to do?
