### ISSUE TITLE
GUI updates

### ISSUE THREAD

**Issue by bob-u** [treeform/fidget#81]
If your program is inline with GUI code, how hard is it to make changes to the GUI? Can it be done with Figma or does it need to be done by editing source code after Initial implementation?

**Comment by treeform** [comment]
You would need to change the source code. Usually what I do is use the Figma plug in and the copy paste the code in the right place. Then Use the VS code diff viewer to put the variables and onClick handlers back.

I had a system where the UI would live in a different file. But that turned out to be pretty hard to reason about. I like the fact that code is code. The Fidget plugin is not an "override" my entire GUI its more of a helper tool.
