### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by wiltzutm** [treeform/fidget#82]
Magnificient project you have here!
It would be super if there was unicode support for the text elements. At the moment when I input unicodes to my fidget text elements they will render empty. I'm not exactly sure if this is a restriction in Figma and not in Fidger per se.

**Comment by treeform** [comment]
Fidget in JS mode has full unicode support because browser does. I support a ton of unicode features but I don't support:
* Emoji
* Character composition
* RTL text like Hebrew or Arabic.
* TTB text like Mongolian Script.
* IME Little box that shows up for typing CJK characters.

Many fonts only support some subset of unicode. I don't have a unicode fall back to system fonts yet. What font were you using and what text where you typing?

**Comment by wiltzutm** [comment]
Yeah I was actually using the font from the fidget examples ("IBM Plex Sans Bold") and it seems it doesn't support the ▲ and ▼ symbols.
The purpose was to create a reusable arrowButton, but it seems that the wisest choice now, based on your suggestions is to stick with images.

**Comment by treeform** [comment]
Yes. Its best to use images for icons. Figma makes it really easy. This is what I do. I can also make sure to get the images pixel perfect.
