### ISSUE TITLE
Why not QML?

### ISSUE THREAD

**Issue by ShalokShalom** [treeform/fidget#91]
After seeing your video, I do wonder why you didn't consider QML, the Qt Design Studio, and that whole, already developed and maintained set of software, instead of relying on non-free software and basically providing only Windows support. 

https://www.qt.io/product/ui-design-tools

You can design interfaces with the Qt Design Studio at least as detailed and easy as with Figma, import assets directly from Blender, Photoshop and Co and can export all of that in QML.

**Comment by bob-u** [comment]
Maybe because QT designer studio is not free:

> Qt Design Studio is available today as a free tool for everyone to try out and evaluate. You will need a commercial Qt developer license to distribute your UIs created with Qt Design Studio. This means, for example, that designers or design companies can use Qt Design Studio for free, as long as the company they’re working for has the necessary commercial Qt licenses for their developers.

**Comment by ShalokShalom** [comment]
Well, Figma is not free and has no backend.
Qt could be free soon and is sure to have multiple backends.
And the Qt Widget Studio, Qt Designer, is free already. 
Thanks

**Comment by ShalokShalom** [comment]
Just for the record: Qt Designer Studio, the tool to develop 2D, 3D and QML applications, does privide a free community edition: https://download.qt.io/official_releases/qtdesignstudio/1.6.0/

Still, with no source code.

**Comment by treeform** [comment]
My main reason for choosing Figma is because it's a modern tool that is popular among UX designers.

Other tools considered where:
* Sketch - Also used a ton by UX designers, I have written export/import system for sketch as well but Figma is just better in my opinion. Sketch also does not work on windows, but Figma does.
* Adobe XD - Not as popular as sketch/figma but I could see using it as well.
* Invision Studio - Very new, but I could see using it as well.
* Adobe Illustrator/Photoshop/InDesign - The old tools used by UX designers. But it does so much, and can be very confusing, many are switching a way from it. Probably will never support.

Qt Designer Studio was never considered simply because its not used by any UX Designers I know. It's also very tied to Qt. If you want to use Qt go use Qt, I can't stop you.

**Comment by ShalokShalom** [comment]
If popularity was the only deciding factor, we would not be using Nim
